name: Test ecr-viewer Container

on:
  pull_request:
    branches:
      - "**"
    paths:
      - containers/ecr-viewer/**
      - containers/fhir-converter/**
      - .github/workflows/container-ecr-viewer.yaml
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - main
    paths-ignore:
      - pyproject.toml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CONTAINER: ecr-viewer
  NODE_VERSION: 22 # Adjust the Node.js version as needed

jobs:
  javascript-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint javascript for ${{env.CONTAINER}}
        working-directory: ./containers/${{env.CONTAINER}}
        run: |
          npm ci
          npm run lint
          npm run lint:tsc

  test-node-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Install dependencies
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm install
      - name: Run tests
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ env.CONTAINER }}

  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.CONTAINER }} Container
        uses: docker/build-push-action@v6
        with:
          context: ./containers/${{ env.CONTAINER }}
          file: ./containers/${{ env.CONTAINER }}/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  convert-data:
    strategy:
      fail-fast: false
      matrix:
        config: ["AWS_SQLSERVER_NON_INTEGRATED", "AZURE_PG_NON_INTEGRATED"]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Set up env vars
        working-directory: ./containers/${{env.CONTAINER}}
        run: |
          npm run setup-local-env
          ../../setup-env.sh ../orchestration/.env ../orchestration/.env.sample

      - name: Set CONFIG_NAME to ${{ matrix.config }}
        working-directory: ./containers/${{env.CONTAINER}}
        run: |
          sed -i 's/AWS_SQLSERVER_DUAL/${{ matrix.config }}/' .env.local

      - name: Run seed data conversion
        run: npm run convert-seed-data
        working-directory: ./containers/${{env.CONTAINER}}

  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        config_name: ["AWS_SQLSERVER_DUAL", "AWS_INTEGRATED"]

    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install dependencies
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm run test:e2e:install

      - name: Set up env vars
        working-directory: ./containers/${{env.CONTAINER}}
        run: |
          npm run setup-local-env
          ../../setup-env.sh ../orchestration/.env ../orchestration/.env.sample

      - name: Set CONFIG_NAME to ${{ matrix.config_name }}
        working-directory: ./containers/${{env.CONTAINER}}
        run: |
          sed -i 's/AWS_SQLSERVER_DUAL/${{ matrix.config_name }}/' .env.local

      - name: Run seed data conversion
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm run convert-seed-data
        env:
          SEED_DATA_DIRECTORIES: star-wars

      - name: Run local docker and wait for it to be ready
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm run local-docker:silent && ./e2e/waitForUrl.sh localhost:3000/ecr-viewer/api/health-check localhost:8071/health/ready

      - name: Run Playwright tests
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm run test:e2e

      - name: Docker down
        working-directory: ./containers/${{env.CONTAINER}}
        run: docker compose --profile "*" down

      - name: Upload playwright report - Non-Integrated
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: containers/${{env.CONTAINER}}/playwright-report/
          retention-days: 5

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: lighthouse-report
          path: containers/${{env.CONTAINER}}/lighthouse/
          retention-days: 5

      - name: Get docker logs
        if: ${{ !cancelled() }}
        working-directory: ./containers/${{env.CONTAINER}}/e2e
        shell: bash
        run: |
          echo "Saving $container logs"
          docker compose --profile "*" logs --timestamps >& e2e-run.log

      - name: Archive docker logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./containers/${{env.CONTAINER}}/e2e/e2e-run.log
          retention-days: 5

  integration-tests:
    strategy:
      fail-fast: false
      matrix:
        db_type: ["pg", "sqlserver"]

    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install dependencies
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm ci

      - name: Set up env vars
        working-directory: ./containers/${{env.CONTAINER}}
        run: |
          npm run setup-local-env
          ../../setup-env.sh ../orchestration/.env ../orchestration/.env.sample

      - name: upcase db type
        shell: bash
        run: echo "DB_TYPE=$(echo "${{matrix.db_type}}" | tr '[:lower:]' '[:upper:]' )" >> "${GITHUB_ENV}"

      - name: Set config for db type
        working-directory: ./containers/${{env.CONTAINER}}
        run: |
          sed -i 's/AWS_.*_DUAL/AWS_${DB_TYPE}_NON_INTEGRATED/' .env.local

      - name: Run local docker and wait for it to be ready
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm run local-docker:silent && ./e2e/waitForUrl.sh localhost:3000/ecr-viewer/api/health-check

      - name: Run integration tests - ${{ matrix.db_type }}
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm run test:integration:${{ matrix.db_type }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ env.CONTAINER }}

      - name: Docker down
        working-directory: ./containers/${{env.CONTAINER}}
        run: docker compose --profile "*" down
